name: flutter_course
description: Flutter, TDD, Clean Architecture, SOLID e Design Patterns

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  test:  
  mockito: 
  faker: 
  http: 
  mocktail: 
  provider: 
  equatable: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true

flutter_icons: 
  ios: true 
  android: true 
  image_path_android: lib/lib//ui/assets/icon/android.jpeg
  image_path_ios: lib/lib/ui/assets/icon/android.jpeg
  adaptative_icon_background: lib/lib/ui/assets/icon/background.png
  adaptative_icon_foreground: lib/lib/ui/assets/icon/foreground.png
